[build]
  command   = "chmod +x ./node_modules/.bin/* && npm run build"
  publish   = "dist"

[build.environment]
  NODE_ENV  = "development"

[[redirects]]
  from   = "/storybook"
  to     = "/storybook/"
  status = 301
  force  = true
